name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name: make
      run: make
    - run: echo success!
    - name: start program
      run: ./ybxsh 
